import { Student } from "./student.js";

let student1 = new Student('Olha', 'Kurchenko', '1989', [100, 100, 100, 100, 88, 100, 95]);
student1.getAge();
student1.getGPA();
student1.present();
student1.present();
student1.present();
student1.absent();
student1.present();
student1.present();
student1.present();
student1.present();
student1.present();
student1.present();
student1.absent();
student1.present();
student1.present();
student1.present();
student1.present();
student1.present();
student1.present();
student1.absent();
student1.present();
student1.present();
student1.absent();
student1.present();
student1.present();
student1.present();
student1.absent();
student1.present();

student1.averagePresent();
student1.summary();


let student2 = new Student('Anna', 'Levchenko', '1988', [100, 90, 100, 100, 88, 10, 95, 100]);
student2.getAge();
student2.getGPA();
student2.present();
student2.present();
student2.present();
student2.absent();
student2.present();
student2.present();
student2.present();
student2.present();
student2.present();
student2.present();
student2.absent();
student2.present();
student2.present();
student2.present();
student2.absent();
student2.present();
student2.present();
student2.absent();
student2.present();
student2.present();
student2.absent();
student2.present();
student2.present();
student2.present();
student2.absent();
student2.absent();

student2.averagePresent();
student2.summary();